# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configdialog.ui'
#
# Created: Fri Feb  7 20:52:17 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setWindowModality(QtCore.Qt.NonModal)
        Settings.resize(400, 410)
        Settings.setSizeGripEnabled(False)
        Settings.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(Settings)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.general = QtGui.QWidget()
        self.general.setObjectName("general")
        self.tabWidget.addTab(self.general, "")
        self.nikkichou = QtGui.QWidget()
        self.nikkichou.setObjectName("nikkichou")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.nikkichou)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileBox = QtGui.QGroupBox(self.nikkichou)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileBox.sizePolicy().hasHeightForWidth())
        self.fileBox.setSizePolicy(sizePolicy)
        self.fileBox.setObjectName("fileBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fileBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileLabel = QtGui.QLabel(self.fileBox)
        self.fileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.fileLabel.setWordWrap(False)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout_2.addWidget(self.fileLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.fileBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.locEdit = QtGui.QLineEdit(self.fileBox)
        self.locEdit.setObjectName("locEdit")
        self.horizontalLayout.addWidget(self.locEdit)
        self.locBro = QtGui.QToolButton(self.fileBox)
        self.locBro.setObjectName("locBro")
        self.horizontalLayout.addWidget(self.locBro)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.fileBox)
        self.backupBox = QtGui.QGroupBox(self.nikkichou)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backupBox.sizePolicy().hasHeightForWidth())
        self.backupBox.setSizePolicy(sizePolicy)
        self.backupBox.setObjectName("backupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.backupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.backupLabel = QtGui.QLabel(self.backupBox)
        self.backupLabel.setObjectName("backupLabel")
        self.verticalLayout_4.addWidget(self.backupLabel)
        self.cusDirBox = QtGui.QGroupBox(self.backupBox)
        self.cusDirBox.setCheckable(True)
        self.cusDirBox.setChecked(False)
        self.cusDirBox.setObjectName("cusDirBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.cusDirBox)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.cusDirBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cusDirEdit = QtGui.QLineEdit(self.cusDirBox)
        self.cusDirEdit.setText("")
        self.cusDirEdit.setObjectName("cusDirEdit")
        self.horizontalLayout_2.addWidget(self.cusDirEdit)
        self.toolButton_2 = QtGui.QToolButton(self.cusDirBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.verticalLayout_4.addWidget(self.cusDirBox)
        self.verticalLayout_3.addWidget(self.backupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.nikkichou)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exportLabel = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportLabel.sizePolicy().hasHeightForWidth())
        self.exportLabel.setSizePolicy(sizePolicy)
        self.exportLabel.setObjectName("exportLabel")
        self.horizontalLayout_3.addWidget(self.exportLabel)
        self.exportOption = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportOption.sizePolicy().hasHeightForWidth())
        self.exportOption.setSizePolicy(sizePolicy)
        self.exportOption.setObjectName("exportOption")
        self.exportOption.addItem("")
        self.exportOption.addItem("")
        self.horizontalLayout_3.addWidget(self.exportOption)
        self.exportBtn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportBtn.sizePolicy().hasHeightForWidth())
        self.exportBtn.setSizePolicy(sizePolicy)
        self.exportBtn.setAutoDefault(False)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout_3.addWidget(self.exportBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.importLabel = QtGui.QLabel(self.groupBox_2)
        self.importLabel.setObjectName("importLabel")
        self.horizontalLayout_4.addWidget(self.importLabel)
        self.importBtn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importBtn.sizePolicy().hasHeightForWidth())
        self.importBtn.setSizePolicy(sizePolicy)
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout_4.addWidget(self.importBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.nikkichou, "")
        self.appearance = QtGui.QWidget()
        self.appearance.setObjectName("appearance")
        self.tabWidget.addTab(self.appearance, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), QtGui.QApplication.translate("Settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.fileBox.setTitle(QtGui.QApplication.translate("Settings", "Database Location", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("Settings", "Move the database file to a new place.\n"
"Make it portable by placing file in Hazama\'s directory(default),", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.locBro.setText(QtGui.QApplication.translate("Settings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.backupBox.setTitle(QtGui.QApplication.translate("Settings", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.backupLabel.setText(QtGui.QApplication.translate("Settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cusDirBox.setTitle(QtGui.QApplication.translate("Settings", "Custom Backup Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("Settings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Import/Export", None, QtGui.QApplication.UnicodeUTF8))
        self.exportLabel.setText(QtGui.QApplication.translate("Settings", "Export:", None, QtGui.QApplication.UnicodeUTF8))
        self.exportOption.setItemText(0, QtGui.QApplication.translate("Settings", "All diary", None, QtGui.QApplication.UnicodeUTF8))
        self.exportOption.setItemText(1, QtGui.QApplication.translate("Settings", "Selected diary", None, QtGui.QApplication.UnicodeUTF8))
        self.exportBtn.setText(QtGui.QApplication.translate("Settings", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.importLabel.setText(QtGui.QApplication.translate("Settings", "Import:", None, QtGui.QApplication.UnicodeUTF8))
        self.importBtn.setText(QtGui.QApplication.translate("Settings", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nikkichou), QtGui.QApplication.translate("Settings", "Diary", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearance), QtGui.QApplication.translate("Settings", "Appearance", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Settings = QtGui.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

